version: "3.8"
services:
  # tunnelclient:
  #   #container_name: tunnelclient
  #   image: ghcr.io/slntopp/nocloud-tunnel-mesh/client:latest
  #   environment:
  #     TUNNEL_HOST: tunnelserver:8080
  #     DESTINATION_HOST: https://httpbin.org
  #   volumes:
  #     - ./cert:/cert
  # tunnelserver:
  #   #container_name: gprs-server
  #   image: ghcr.io/slntopp/nocloud-tunnel-mesh/server:latest
  #   ports:
  #     - 8080:8080 # tunnel gRPC
  #     - 8000:8000 # DB management gRPC
  #     - 80:80     # HTTP Server
  #   volumes:
  #     - ./cert:/cert


  tunnelclient:
    #container_name: tunnelclient
    image: ghcr.io/ewrvp7lv7/grpcsockettest/client:latest
    environment:
      TUNNEL_HOST: tunnel.nocloud.slnt-opp.xyz:443


  # # toxiproxy.json ->toxics not work!
  # # https://github.com/shopify/toxiproxy
  # toxiproxy:
  #   container_name: toxiproxy
  #   image: ghcr.io/shopify/toxiproxy:latest
  #   command: -host=0.0.0.0 -config /config/toxiproxy.json
  #   restart: always
  #   hostname: localhost
  #   network_mode: "host"
  #   expose:
  #     - 8474
  #     - 53000
  #     - 53001
  #     - 53002
  #   volumes:
  #     - ./config:/config